name: mobilyzer
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - ipykernel
  - pip:
      - numpy==1.24.4
      - pandas==2.0.3
      - scipy==1.10.1
      - scikit-learn==1.3.0
      - h5py==3.9.0
      - hdf5storage==0.1.19
      - jupyterlab==4.0.5
      - ipywidgets==8.1.0
      - matplotlib==3.7.2
      - seaborn==0.13.2
      - pillow==10.0.0
      - imageio==2.35.1
      - opencv-python==4.11.0.86
      - tqdm==4.67.1
      - einops==0.6.1
      - timm==1.0.14
      - spectral==0.23.1
      - yacs==0.1.8
      - tabulate==0.9.0
      - gdown==5.2.0
      - torchsummary==1.5.1
      - torchinfo==1.8.0
      - scikit-image==0.21.0
